function interPoint = LinesIntersection(lineModelA, lineModelB)
    syms pa_x pa_y pa_z pb_x pb_y pb_z mua mub;
    sol = solve([[pa_x pa_y pa_z] == lineModelA.Origin + mua*lineModelA.Normal,...
        [pb_x pb_y pb_z] == lineModelB.Origin + mub*lineModelB.Normal,...
        dot([pa_x pa_y pa_z]-[pb_x pb_y pb_z], lineModelA.Normal) == 0,...
        dot([pa_x pa_y pa_z]-[pb_x pb_y pb_z], lineModelB.Normal) == 0,...
    ]);

    interPoint = ([double(sol.pa_x) double(sol.pa_y) double(sol.pa_z)] + [double(sol.pb_x) double(sol.pb_y) double(sol.pb_z)])/2;
end

